### ISSUE TITLE
Android N crash

### ISSUE THREAD

**Issue by rafalniski** [Estimote/Android-SDK#162] opened 2016-08-12 12:04 UTC
Hi,

today we started noticing that Estimote SDK crashes on Android N (Nexus 5X devices). Here is the log from Fabric:

http://crashes.to/s/e995e73fd3a

Any idea what can be wrong?

**Comment by pawelDylag** [comment] 2016-08-16 06:53
Hi @rafalniski 

From your logs I conclude, that you have 'FORCE_OLD_SCANNING_API' flag set to `true`.  Could you please tell me if I am right? If so, then could you turn it off and check once again if that problem occurs? We have released some scanning fixups and upgrades for Android 5.0+., which might have fixed your problem, but this flag is getting into way. 

Anyway, thanks a lot for reporting that.  We're actually preparing support for Android N and if your problem will turn out to be much more severe, then we will fix it in the next release.

Have a nice day!

**Comment by rafalniski** [comment] 2016-08-16 07:05
Do you mean that line  `<meta-data android:name="force_old_scanning_api" android:value="true" />` in the manifest? We do not have that in our project. Although, the version that crashes is using SDK 0.10.4, if it makes any difference.

**Comment by pawelDylag** [comment] 2016-08-16 07:13
Ok, so the last thing to deduct - Scanning fixups were made in sdk version 0.10.5 - according to our [Changelog](https://github.com/Estimote/Android-SDK/blob/master/CHANGELOG.md). So could you check if this problem still occurs? I need to know if your problem has been fixed by our further changes. If not, I will add this to our scope and we will investigate it deeply. Also, could you tell me which version of Android N preview are you using?

We will figure this problem out, don't worry :)

**Comment by rafalniski** [comment] 2016-08-17 08:38
It still occurs on 0.11.0.

**Comment by pawelDylag** [comment] 2016-08-17 13:01
@rafalniski 

Ok, we will look deeper into it.  For now, we cannot reproduce this bug on our devices with Android N. I'll update you about any changes.

**Comment by pawelDylag** [comment] 2016-09-22 08:55
Hey @rafalniski 
Could you tell me if this bug appears on version 0.12.0+ ? 
If not, I will close this issue.

**Comment by rafalniski** [comment] 2016-09-22 13:45
Looks like it's gone.

**Comment by pawelDylag** [comment] 2016-09-22 13:48
Great! Please notify me about any problem you encounter. Closing this issue.

**Closed by pawelDylag** 2016-09-22 13:48 UTC
