### ISSUE TITLE
SecureBeaconRegion doesn't work with null proximity UUID

### ISSUE THREAD

**Issue by xcastoreo** [Estimote/Android-SDK#211] opened 2017-04-19 08:11 UTC
Hi,

it seems that `new SecureBeaconRegion("my_region", null, null, null);` does not work:
> java.lang.NullPointerException: Attempt to invoke virtual method 'long.java.util.UUID.getMostSignificantBits()' on a null object reference

In the `ScanFilter createSecureRegionfilter(UUID uuid)` method, there is **no check for null UUID** before working on it.

JavaDoc page about SecureBeaconRegion:
[http://estimote.github.io/Android-SDK/JavaDocs/com/estimote/coresdk/observation/region/beacon/SecureBeaconRegion.html](url)

**Comment by pawelDylag** [comment] 2017-04-19 08:27
Hello @xcastoreo !

My fault - will be fixed in the next release :) Thanks for reporting that! Here is a cookie for you 🍪 

Cheers!

**Comment by xcastoreo** [comment] 2017-04-19 08:37
Cool :)

Just another question:
when I enter a UUID (for example `UUID.fromString("1E5D4373-E741-4F68-73EF-375ED2EDBE54")`) to create the secure region, the app's crashes and the Android Device Monitor shows:

> `E/EstimoteSDK: LollipopBluetoothAdapter$1.onScanFailed:269 Unable to start BLE scanning. Error code 3`

So it's that an other bug or am I doing it wrong?

**Comment by pawelDylag** [comment] 2017-04-19 08:48
This may be connected to the bug above. There is a problem with filtering, so any UUID will got parsed wrong. I'm fixing this right now :)

**Comment by pawelDylag** [comment] 2017-04-19 14:50
Hey @xcastoreo !

Fix was introduced in `version 1.0.2` :) Because `SecureBeaconRegion` needs at least proximity UUID to behave properly, I disabled possibility to use `null` UUID object. 
Also, the problem with `Error code 3` is a typical problem on some phones. It is because our SDK tries to set many low-level filters to match SecureRegions and some phones can't handle that. I improved it and it should work now for every device :) 
Please tell me if everything is alright now.
Cheers!

**Comment by xcastoreo** [comment] 2017-04-20 08:09
Hey @pawelDylag,

Thanks you for your reactivity ;)

I'm trying to scan for non secured beacons with the new 1.0.2 release:
`beaconManager.connect(new BeaconManager.ServiceReadyCallback() {
  @Override
  public void onServiceReady() {
    Log.i(TAG, "Starting Ranging " + BEACONS);
    beaconManager.startRanging(BEACONS);
  }
});`

But the Android Device Monitor doesn't say the "`Starting Beacon ranging`":

> I/NearestBeaconManager: Starting Ranging BeaconRegion{identifier=secured_beacons, proximityUUID=null, major=null, minor=null, secure=false}

My Bluetooth is enabled, and they are both non-secured and secured beacons all around...

**Comment by xcastoreo** [comment] 2017-04-20 08:37
So,

the ranging is starting right, but it always returns an **empty list** of beacons.
The same code works well with the `1.0.1` SDK version.

**Comment by pawelDylag** [comment] 2017-04-20 09:50
Are you scanning for both secure & non-secure beacons?
Could you try switching off hardware filters ? In your Android Manifest add below `Application` tag: ```<meta-data android:name="disable_hardware_filtering" android:value="true" />```
Does it change anything? Also please let me know how do you specify your secure region. Are you using random UUID? Or the one that is encrypted?

**Comment by xcastoreo** [comment] 2017-04-20 10:12
- I am only scanning for non-secure beacons (we will see secure beacons later ;)),
- adding the `<meta-data android:name="disable_hardware_filtering" android:value="true" />` tag
does not change anything, the list is always empty,
- when I create a secure-region, I do this:
`private static final SecureBeaconRegion BEACONS = new SecureBeaconRegion("secured beacons", UUID.fromString("XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"), null, null);`

**Comment by xcastoreo** [comment] 2017-04-24 08:03
Hey @pawelDylag,

I've tried to range non-secured beacons with:

1. `BeaconRegion("all beacons", null, null, null);`
2. `BeaconRegion("my beacon", UUID.fromString("XXXXXXXX-XXXX-XXXX-XXXX-XXXXXX"), null, null);`

and range secure beacons with:

3. `SecureBeaconRegion("my secure beacon", UUID.fromString("XXXXXXXX-XXXX-XXXX-XXXX-XXXXXX"), null, null);`

In 1.0.1, the **1.** scans for both non-secure and secure beacons. The **2.** scans only for the beacon requested (beeing secure or not). And **3.** doesn't works.

But always returning empty lists in 1.0.2...

**Comment by jsearight** [comment] 2017-04-27 15:06
We are experiencing this exact same issue.

We are able to see unclaimed, unmodified beacons with v1.0.2, but not our own.

Do you have an estimate for this fix?

**Comment by agra1992** [comment] 2017-04-27 21:25
Hey all,

Looks like I've run into the exact same issue as well. I'm trying to range for beacons in my Nativescript app which uses Estimote SDK version 1.0.2. However, moving to the latest version of the SDK seems to always return an empty list of beacons.

Also, adding the `<meta-data android:name="disable_hardware_filtering" android:value="true" />` hasn't resolved the issue. :(

Is there any fix available for this?

Regards,
AK

**Comment by pawelDylag** [comment] 2017-05-02 13:00
Hello guys!

Please check the fresh version of our SDK `1.0.3` and let me know if the problem is gone. If not, we will proceed further and schedule it to the next release :)

Have a nice day!

**Comment by agra1992** [comment] 2017-05-02 15:24
Hey Pawel,

Thanks for the reply. I love how you guys get back so quickly with resolutions to any problem. 👍 

I will test the app with v1.0.3 and let you know if the problem is gone.

Have a great day ahead and regards,
AK

**Comment by xcastoreo** [comment] 2017-05-02 15:47
Hey @pawelDylag,

happy to test the new 1.0.3! But I can't see any of my non-secure beacons ;(

**Comment by agra1992** [comment] 2017-05-02 17:02
I tested the v1.0.3. Still cannot see any ranged beacons. However, ConfigurableDevicesScanner works fine as always.

**Comment by xcastoreo** [comment] 2017-05-03 09:01
[versions.pdf](https://github.com/Estimote/Android-SDK/files/972849/versions.pdf)

**Comment by pawelDylag** [comment] 2017-05-04 09:17
Ok guys, this is really interesting. According to our test suite, ranging works well on all the phones. Although we do not have the coverage of all available Android devices. I need to know:
1. Phone models you did test on
2. Your Beacons info - type, firmware & hardware version, TX power/ Interval of iBeacon packet, 
3. Any helpful snippets - like your `BeaconManager` setup and/or ranging listener. 

We will figure it out, don't worry :)

**Comment by jitongkai** [comment] 2017-05-04 09:57
i has different firmware and hardware version beacons，such as:
1. firmware version:  A3.2.0  hardware version: D3.3， （can not discover by ranging, but can discover by use sdk version 1.0.1）
2. firmware version: 4.9.1 hardware version: F3.3, ( can discover by ranging, sdk version 1.0.1 and 1.0.3  either is fine)

**Comment by xcastoreo** [comment] 2017-05-04 10:08
My side:

1. Samsung SM-G360F with Android 5.0.2,
2. type: Proximity Beacon
name:
color:
geolocation:
indor location:
tags:
meshgroup:
Remaining Battery Life: 2 months
Basic Battery Saving: Off
Smart Battery Saving: On
Motion Detection: On
Motion Only Broadcasting: Off
Motion Only Broadcasting Delay: 0 ms
Flip To Sleep: On
Automatic Firmware Update: Off
Firmware Version: 3.2.0
Hardware Version: D3.4
Primary Packet Type: Estimote Default
Proximity UUID:
Major:
Minor:
Security UUID: Off
Broadcasting Power: Strong (4dBm)
Maximum Range: ~ 70 m / 230 ft
Advertising Interval: 100 ms
3. I'm using a copy of the **ProximityContent** sample.
I can see the `ConfigurableDevice` packets of this same beacon.

**Comment by pawelDylag** [comment] 2017-05-04 10:29
@xcastoreo , @jitongkai 

Ok, wonderful insight. Now I know that both of you are using our old D3.X beacons. We are really moving forward with development and all the tests are being made on newer beacons. I will check ranging for older devices and will keep you informed. I will also compare changes from 1.0.1 and 1.0.3, maybe I made some mistakes when updating. 
Also, I really recommend buying newer beacons (like proximity, or even location beacons). They are way cooler then old ones :)

**Comment by manishpatelgt** [comment] 2017-05-05 08:34
I faced the same issue. I have Google Pixel with Android 7.1.2.

It's working fine in Nexus 5 with Android 5.1.1 and Samsung Galaxy S6 with Android 6.0.1.

I am using Estimote SDK 1.0.3 @pawelDylag

**Comment by agra1992** [comment] 2017-05-05 15:18
Hey Pawel,

Just to confirm, I'm using D3.X beacons as well for development purposes. I'm also using a pretty old device Samsung SM-G531F. I will also try running my app on a Nexus 6 and check if it's working on that device. Also, my Android version is at 5.1.1 (pretty old as well :P).

Let me know if I need to upgrade my mobile device to be able to range for the beacons.

Regards,
AK

**Comment by sw-tt-devalpatel** [comment] 2017-05-18 05:48
Hey @pawelDylag 

I am using Job Service for scanning beacons in application Kill Mode. I am using D3.X version beacons and they are not able to discovered in onBeaconsDiscovered with Job Service but it's working fine with Activity.

Estimote Version used 1.0.3
Android OS Version 6.0.1
Device Nexus 5

If I am replace estimote library to version 1.0.1 then I will got results in onBeaconsDiscovered.
Is their any issue with latest revision?

Regards,
Deval Patel

**Comment by xcastoreo** [comment] 2017-05-18 07:11
Hey @pawelDylag,

any news about this?
We would like to use both beacon ranging & packet discovery with our D3.X beacons :)

**Comment by RafaelSermenho** [comment] 2017-06-12 19:04
Hi guys! I'm having the same problem using D3.X beacons on Samsung Galaxy S7 and Samsung Galaxy S8 (Android N) devices. Monitoring is working with version 1.0.1 but not with version 1.0.3.

**Comment by xcastoreo** [comment] 2017-06-22 09:58
Hi @pawelDylag,

any news for this hot topic? ><
We are going to need this feature very quickly, can you inform us about the time you will need to fix it?

Thanks!

**Comment by ng28** [comment] 2017-07-07 14:33
Hi @pawelDylag, I would like to know when this bug will be fixed.

**Comment by pawelDylag** [comment] 2017-07-10 07:00
Hey all!

Sorry for the delays - we've got tons of work to do here :)
We'll be investigating this problem in the upcoming week - D3.X beacons are really old and they have low priority on our task list. But we'll try our best to fix the problem introduced by mistake in `1.0.3`. If you need only stable ranging/monitoring for those old beacons, you can switch back to `1.0.1` for now. 
We'll keep you informed about that :)

**Comment by xcastoreo** [comment] 2017-07-11 15:28
@pawelDylag,

I'm actually doing this, just unable to call the _SecureRanging_ on Android and on iOS with the same JavaScript function, and on Android scanning for both secure and non secure beacons.
Waiting for news ;)

**Comment by xcastoreo** [comment] 2017-07-13 08:26
Hey,
I have little news:
in Estimote Android SDK version **1.0.1**, the _Secure Ranging_ works only when we scan for an **empty** `BeaconRegion()`. Defining a non-null `UUID` makes the _Secure Ranging_ fail.
The simple _Ranging_ always works.

**Comment by xcastoreo** [comment] 2017-07-19 10:53
What's new?

I have to implement the **secure ranging** with the D3.X beacons, but on Android the device is scanning both secure and non-secure beacons. So it's not really secure if someone **discovers** the true UUID, because he will be able to **clone** it :(

**Comment by pawelDylag** [comment] 2017-07-19 11:29
Hey! 

We have released version `1.0.9` with slightly changed scanning mechanism on Nougat devices and fixed support for old D3.X beacons :)

**Comment by xcastoreo** [comment] 2017-07-19 12:14
Cool,

I will see that ;)

Ty

**Comment by xcastoreo** [comment] 2017-07-19 13:44
Hey @pawelDylag,

in version `1.0.9`, the scan of a `SecureBeaconRegion` is crashing and says:

```
E/EstimoteSDK: LollipopBluetoothAdapter$1.onScanFailed:269 Unable to start BLE Scanning. Error code 3
```

while a `BeaconRegion` scan works.

Also, it seems to be the BeaconManager -1 error code:

```
ERROR_COULD_NOT_START_LOW_ENERGY_SCANNING
```

**Comment by xcastoreo** [comment] 2017-07-20 13:54
Hi,

new from my tests:

* the ranging of a **SecureBeaconRegion** doesn't crash,
* this ranging gives the Secure Beacons but also the **non-secure Beacons**...

So the issue was previously:

* [ ] `startRanging(SecureBeaconRegion)` was crashing,
* [ ] it delivered nothing,
* [x] `startRanging(BeaconRegion)` was not crashing,
* [ ] it delivered both **non-secure** and **secure** beacons.

And after the `1.0.9`, we have:

* [x] `startRanging(SecureBeaconRegion)` is not crashing,
* [ ] it delivers both **non-secure** and **secure** beacons,
* [x] `startRanging(BeaconRegion)` is not crashing,
* [x] it only delivers non-secure beacons.

A last effort and we will get it ;)

**Comment by pawelDylag** [comment] 2017-07-20 13:57
Hey @xcastoreo 

Thanks for the report - we'll make sure Secure region won't report non-secure beacons in the next release :)

Cheers!

**Comment by xcastoreo** [comment] 2017-08-03 07:25
Hey @pawelDylag,

I'm still here with my annoying issue, is there any news?

**Comment by shlok2iid** [comment] 2017-08-10 09:05
Hi Pawel,

I am stile get enter/exit problem in newer version 1.0.9, 1.0.11, 1.0.12.
Please help me thanks is adwance.

**Comment by pawelDylag** [comment] 2017-11-24 13:36
I encourage you to try our new **ProximitySDK** 🚀 - it is dedicated for creating proximity interactions with our beacons - its main focus is to deliver the reliable enter/exit experience according to a different zones of beacons, based on our own data-science, and Estimote Monitoring packet. 
**It works extremely well with Android 5.0-8.0 devices** (full support for Nougat, and Oreo included), and also allows you to configure it to keep scanning in the background.

As it comes for security, there is no support for it in the ProximitySDK, **yet** ;)

Here is the official repository page ->  https://github.com/Estimote/Android-Proximity-SDK

Also, we keep posting updates about the progress of our development [**on this thread at our forums**](https://forums.estimote.com/t/estimote-android-sdk-official-progress-reports/7450). 
**I encourage you to track it in order to be super up-to-date** :)

Please, check the mentioned [new SDK](https://github.com/Estimote/Android-Proximity-SDK) - the current SDK will soon be deprecated, and we will support only critical issues for some time.

**Closed** 2017-11-30 13:20 UTC
Labels: bug
