### ISSUE TITLE
Unable to get telemetry information from Estimote Stickers

### ISSUE THREAD

**Issue by jevora** [Estimote/Android-SDK#171] opened 2016-09-16 11:18 UTC
Hi!

I'm trying to get telemetry information from the stickers but I haven't managed to do it. After following the tutorials and reading about some issues I had before the stage at which I am right now, I have reached to this code:

```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EstimoteSDK.initialize(getApplicationContext(), "real id taken from the cloud", "real token taken from the cloud");
        final BeaconManager beaconManager = new BeaconManager(this);
        beaconManager.setTelemetryListener(new BeaconManager.TelemetryListener() {
            @Override
            public void onTelemetriesFound(List<EstimoteTelemetry> telemetries) {
                for (EstimoteTelemetry tlm : telemetries) {
                    Log.d("TELEMETRY", "beaconID: " + tlm.deviceId +
                            ", temperature: " + tlm.temperature + " °C");
                }
            }
        });
        beaconManager.connect(new BeaconManager.ServiceReadyCallback() {
            @Override
            public void onServiceReady() {
                beaconManager.startTelemetryDiscovery();
            }
        });
    }

    @Override
    protected void onResume() {
        super.onResume();
        SystemRequirementsChecker.checkWithDefaultDialogs(this);
    }
```
Once I execute this code, I'm not able to see more than:

> 09-16 11:03:21.650 4990-5003/com.example.jevora.estimote D/ScanRecord: parseFromBytes
> 09-16 11:03:21.650 4990-5003/com.example.jevora.estimote D/ScanRecord: first manudata for manu ID

I cannot see in the logcat any telemetry message nor an exception. I have checked using Estimote app that the sticker I'm using had it enabled and with the frequencies correctly set.

Do you know what may be the problem?

Thanks

**Comment by pawelDylag** [comment] 2016-09-16 12:59
Hello @jevora 

At first we need to be 100% sure that your sticker is advertising telemetry packets. As far as I know, our Android App doesn't allow to turn telemetry on stickers yet. I conclude, that you checked that on our cloud, or iOS app. If so, please make sure that you can connect to your sticker. 
Secondly, I don't recall any "first manudata" log in our SDK - is it flooding your logcat? If so, I think this comes from a lower level. I remember having this log once on a Samsung device - could you tell me if you are using it? 
Also, make sure that your sticker has "motion only advertising" disabled. Or try shaking it constantly while scanning with your app. 

I'm waiting for your response and we will proceed further :)

**Comment by jevora** [comment] 2016-09-16 13:15
Hello @pawelDylag 

Thanks for the fast answer. Yes, Samsung S5 :)

I saw in the Android APP that Advertising intervals (still and motion) were set to 2588 and 1294 respectively. Primary packet type is nearable and Estimote Default as secondary. This is what I can see in the web: 

![image](https://cloud.githubusercontent.com/assets/5517331/18586967/6b2003f0-7c17-11e6-8b58-060eed01ab7f.png)

Is there any problem with the config?.

Thanks!

**Comment by pawelDylag** [comment] 2016-09-16 13:32
Ok, I know what the problem is :)
Stickers don't advertise general telemetry packet. All telemetry information is contained in it's Nearable packet. So in order to get telemetry data from your sticker, you need to setup `NearableListener` and start `NearableDiscovery` - all your data will be inside `Nearable` object. 
Let me know if this solution was helpful :)

**Comment by jevora** [comment] 2016-09-19 08:40
Hi @pawelDylag 

Yes, I have managed to read the measures taken from the stickers. Thanks!

I've checked the documentation and I've seen the fields x-y-zAcceleration. These fields are variating through the measures when sticker is being moved. I would like to know what is the precision they have. 

I've put it on a table and hit the table and measures are rarely changed. It seems not to be very sensitive like sensors on phones and tables, am I right? I have removed the plastic of the sticker to see if it was absorbing some energy but results are similar. Is this right or I should calibrate them somehow?

Best

**Comment by pawelDylag** [comment] 2016-09-19 08:53
Hello once again @jevora 

As far as I know, sticker is sending it's packet every 2,5 s. So if you hit the table, there is a low possibility that the sensor will get your measurement and send it in a packet. So no, for measuring single hits, sticker is not very precise. Bear in mind the delay caused by packet transmission frequency and a time for it to reach your phone antenna.

If you have a questions about use-cases for your sticker, feel free to contact our support here: https://forums.estimote.com/  
For any questions about our SDK or Android  - I am here to help you :)

**Closed** 2016-09-19 12:27 UTC

**Comment by KeyurPatel94** [comment] 2017-04-13 05:35
@pawelDylag 
                         hey you have such tutorial for android as such as ios for android stickers 
I am not able to find and I stuck into it please help. I want to measure motion, temperature, enter/exit region. I want UI for android nearable.
Waiting for your answer.
Thanks in advance, and hope you we you will pick me out from this issue
