### ISSUE TITLE
beacon monitoring

### ISSUE THREAD

**Issue by DayronIG** [Estimote/Android-SDK#132] opened 2015-11-06 21:14 UTC
i have a problem i using your SDK but for some reason we keep getting in and out of region even when I am not moving,.

What is the reason for this to happen, I'm in the warehouse and notified me that I left the region and tells me three seconds to enter back into the region.

**Comment by wiktor** [comment] 2015-11-07 09:09
Duplicate of #130. That one is tracking issue for all monitoring related problems.

**Closed by wiktor** 2015-11-07 09:09 UTC
Labels: duplicate
