### ISSUE TITLE
onEnteredRegion/onExitedRegion called milliseconds apart

### ISSUE THREAD

**Issue by mcummins** [Estimote/Android-SDK#143] opened 2016-03-01 16:28 UTC
On some Android devices I see `onExitedRegion` called milliseconds after `onEnteredRegion`. I've seen this behaviour intermittently on several Android devices, but on some devices it happens continuously.

I have seen this problem on two different devices so far:
- Samsung Galaxy A3 (SM-A300FU) running Android 5.0.2
- Vodafone Smart Ultra 6 running Android 5.1

Both with:
estimote:sdk:0.9.7@aar
Beacons broadcasting every 450ms, close to the phone.

More detailed writeup in the forums [here](https://forums.estimote.com/t/onenteredregion-onexitedregion-called-milliseconds-apart/3149).

**Comment by maddie** [comment] 2016-03-04 02:20
I guess this is related to #130, it's been some time already..

**Comment by Poberro** [comment] 2016-03-12 21:37
Duplicate of #130. That one is tracking issue for all monitoring related problems.
Anyway new SDK version 0.10.0 has been released that includes many changes to region monitoring. While testing it, we never experienced that onExit and onEnter are called in milliseconds apart on all devices we have.

**Closed by Poberro** 2016-03-12 21:37 UTC
