### ISSUE TITLE
Unable to connect to location beacons after 1.0.11 and 4.13.0 updates

### ISSUE THREAD

**Issue by nathanprayzo** [Estimote/Android-SDK#244] opened 2017-07-31 15:05 UTC
After updating my android SDK from 1.0.8 to 1.0.11, I connected to a location beacon and successfully updated its firmware from 4.11.0 to 4.13.0 After updating the firmware I am no longer able to connect and read settings from beacons.

Android logcat shows the following information:
```
07-31 10:27:59.150 4764-4764 D/EstimoteSDK: DeviceConnectionInternal.changeState:193 Changing internal connection state from CONNECTING to CONNECTED
07-31 10:27:59.151 4764-4764 D/EstimoteSDK: FullConnectionStrategy.authenticateDevice:66 Authenticating device
07-31 10:28:00.278 4764-4764 D/EstimoteSDK: FullConnectionStrategy.checkDeviceVersion:83 Checking device version and available settings
07-31 10:28:00.384 4764-10002 D/EstimoteSDK: FullConnectionStrategy.synchroniseDeviceSettingsWithCloud:105 Synchronizing device with cloud...
07-31 10:28:00.543 4764-4764 D/EstimoteSDK: DeviceCloudSyncEngine.saveSettingsToDevice:82 Saving settings to device
07-31 10:28:00.562 4764-4764 W/EstimoteSDK: DeviceCloudSyncEngine$2.onFailure:122 Unable to synchronise setting: NFC_DATA Reason: NdefMessage size must be less than 256 bytes. Use validate() to validate entered value.
07-31 10:28:00.565 4764-4764 W/EstimoteSDK: DeviceCloudSyncEngine$2.onFailure:122 Unable to synchronise setting: LINK_NETWORK_WEB_LINK_ID Reason: Invalid value 0 for LINK_NETWORK_WEB_LINK_ID
07-31 10:28:05.985 4764-485 W/EstimoteSDK: DeviceCloudSyncEngine$2.onFailure:122 Unable to synchronise setting: MESH_SETTINGS_LIST Reason: Error INVALID_REGISTER_ID  ,register=3087)
07-31 10:28:07.107 4764-10002 W/EstimoteSDK: DeviceCloudSyncEngine$2.onFailure:122 Unable to synchronise setting: GPIO_NUMBER_2_CONFIG Reason: Error INVALID_VALUE  ,register=b2)
07-31 10:28:07.204 4764-4777 W/EstimoteSDK: DeviceCloudSyncEngine$2.onFailure:122 Unable to synchronise setting: GPIO_NUMBER_3_CONFIG Reason: Error INVALID_VALUE  ,register=b3)
07-31 10:28:07.594 4764-6662 D/EstimoteSDK: FullConnectionStrategy$4$1.onSuccess:112 Device synchronized!
07-31 10:28:08.696 4764-4764 E/DisplayBeacon: Failed connecting to beacon with id'[60ffb2380db40d50110119cfa1bf1a3e]' : com.estimote.mgmtsdk.common.exceptions.DeviceConnectionException: java.lang.UnsupportedOperationException: JsonNull
07-31 10:28:09.077 4764-4764 D/EstimoteSDK: DeviceCloudSyncEngine$3$1.success:161 Device status updated
```

When attempting to connect to the beacon using Estimote app from my samsung s5 (Android 6.0.1), it first indicated that I was not the owner of the beacon even though it appeared on my estimote cloud. Attempting to "Claim" the device resulted in the error message "Claim failed due to server error. Please try again in a few minutes". Inspecting the logs revealed a "401 unauthorized" error message, so I logged out and back into the estimote app which fixed the issue of the beacon not being associated with my account.

Unfortunately the estimote app was still unable to connect to the beacon. The app displayed 'Connecting' but then switched to "Disconnected. Tap to connect" even though the beacon's LED continues to flash. Tapping the screen does not appear to result in a reconnection attempt, and logcat doesn't show anything relevant (just InputReader acknowledging the touch event). The only logging statements that appear relevant during the time the connection is disconnected are:
```
07-31 10:51:25.290  9902 10068 W EstimoteSDK: DeviceCloudSyncEngine$2.onFailure:122 Unable to synchronise setting: MESH_SETTINGS_LIST Reason: Error INVALID_REGISTER_ID  ,register=3087)
```

I suspect if I were able to turn EstimoteSDK on debug I would be able to get more insight into the issue. Is there anyway to do without compiling Estimote app from source and adding this option?

**Comment by nathanprayzo** [comment] 2017-07-31 15:20
I should note that when attempting to connect to beacons from my android app, the behavior appears identical to when the estimote app is attempting to connect (connection fails but beacon LED remains blinking).

Assuming the underlying cause of the connection issue in Estimote app and my app are the same, I believe the following exception is the root cause:
```
07-31 10:28:08.696 4764-4764/com.trimble.ag.beaconmanager E/DisplayBeacon: Failed connecting to beacon with id'[60ffb2380db40d50110119cfa1bf1a3e]' : com.estimote.mgmtsdk.common.exceptions.DeviceConnectionException: java.lang.UnsupportedOperationException: JsonNull
```

**Comment by wafel82** [comment] 2017-07-31 18:58
Hi,
@nathanprayzo -  You've right the root cause of the broken connection is the error related to the 'JsonNull' :
```(...) com.estimote.mgmtsdk.common.exceptions.DeviceConnectionException: java.lang.UnsupportedOperationException: JsonNull```
This issue reveals when sdk tries to connect to the beacon without mesh network configured.
To work-around this problem - Use Estimote cloud to configure mesh network for your device (such mesh may contain just single device you are trying to connect to) and then re-connect to the beacon.
We already working hard to fix this issue - so stay tuned :) 
If everything goes well, new release with bug-fix included will be pushed out tomorrow

Regards
Wojtek

**Comment by nathanprayzo** [comment] 2017-07-31 19:31
Thanks @wafel82. I appreciate your prompt response and the provided work-around.

**Comment by wafel82** [comment] 2017-08-01 14:54
Hi, 
Fix for the issue is available in latest SDK version - 1.0.12. 
It's available on JCenter. Please update Your buld.gradle with:
```compile 'com.estimote:sdk:1.0.12'```

Regards
Wojtek

**Comment by nathanprayzo** [comment] 2017-08-01 15:12
Confirmed the issue has been resolved - very impressive time to resolution, thank you!

**Comment by wafel82** [comment] 2017-08-01 18:33
Hi, 
Good to hear that fix is working as expected :)
I'm closing the issue then.

Regards
Wojtek

**Closed by wafel82** 2017-08-01 18:33 UTC
