### ISSUE TITLE
Update foreground scan period for  Nearables

### ISSUE THREAD

**Issue by SelimaCurci** [Estimote/Android-SDK#206] opened 2017-04-03 13:05 UTC
Hi, 
I need to update the foreground scan period when scanning the estimote stickers (slower or faster depending on certain conditions), but despite I put
         beaconManager.setForegroundScanPeriod(10000,5000);
into the nearableListener, the nearable listener is still being called every second.

I know the ForegroundScanPeriod is intended mostly for use with iBeacon, so the Nearable scanning might turn out not to be affected by this option.

I don't understand because the first time that I permorm the setting it works (for example  the ForegroundScanPeriod to (5s, 2s)) but it doesn't allow to be updated later. 
This feature it would be really helpful to avoid scanning too frequently when no is needed.

Thanks!

**Comment by pawelDylag** [comment] 2017-04-03 16:40
Hello @SelimaCurci 

I deduce that you are using our newest SDK - it seems like a bug, and will be fixed in next release soon :) Thanks for reporting that!

If it comes to the scanning types in our newest SDK, take a look at our basic concept explanation [here](https://github.com/Estimote/Android-SDK#basic-concepts) - it might come in handy :)

Have a nice day!

**Comment by SelimaCurci** [comment] 2017-04-04 07:55
Yes I'm using the versione 0.16.0. Does it works in earlier versions? I think it is an essential feature.

Have a nice day too!

**Comment by pawelDylag** [comment] 2017-04-04 08:01
Helo @SelimaCurci 

The newest version is 1.0.0 - check out the migration guide [here](https://github.com/Estimote/Android-SDK/blob/master/Docs/switching_to_1.0.0.md). 
The issue is already fixed and is waiting for next release (soon) :)

**Comment by SelimaCurci** [comment] 2017-04-05 08:03
Great! Thank you :)

**Comment by pawelDylag** [comment] 2017-04-11 10:16
Fixed in `1.0.1`

**Closed by pawelDylag** 2017-04-11 10:16 UTC
Labels: bug
