### ISSUE TITLE
Samsung Android 5.1.1 fail to scan Secure UUID beacons

### ISSUE THREAD

**Issue by loc02998375** [Estimote/Android-SDK#172] opened 2016-09-18 23:44 UTC
I encountered scanning errors on a number of Samsung phones running Android 5.1.1, these devices fail to scan for beacon with secure UUID and have no issue scanning for non secure UUID iBeacons. The tested devices were: Samsung Galaxy S6 Edge (failed), Samsung Galaxy Note Edge (failed), Samsung Galaxy S6 Edge Plus (worked), Sony and Nexus phones (worked).

Here are the device logs:
`com.estimote.sdk.BeaconManager.disconnect:281 Not disconnecting because was not connected to service
com.estimote.sdk.service.BeaconService.onCreate:305 Creating service
com.estimote.sdk.service.internal.LollipopBluetoothAdapter.updateFilters:205 Filters updated: 0 filters
com.estimote.sdk.service.BeaconService.startMonitoring:444 Starting monitoring: SecureRegion{identifier=cabfare-com-au, proximityUUID=5a67df64-6fcf-11e6-8b77-86f30ca893d3, major=null, minor=null, secure=true}
com.estimote.sdk.service.internal.LollipopBluetoothAdapter.updateFilters:205 Filters updated: 16 filters
com.estimote.sdk.service.internal.LollipopBluetoothAdapter$1.onScanFailed:160 Unable to start BLE scanning. Error code -99
com.estimote.sdk.service.internal.LollipopBluetoothAdapter$1.onScanFailed:163 Detected hardware filters problem (too many filters). Switching hardware filters off.
com.estimote.sdk.service.internal.LollipopBluetoothAdapter$1.onScanFailed:160 Unable to start BLE scanning. Error code 1
com.estimote.sdk.service.BeaconService.stopScanning:582 Stopping scanning`

**Comment by pawelDylag** [comment] 2016-09-19 08:33
Hello @loc02998375 !

The problem is with Samsung BLE stack - it can't handle many hardware filters at once. I can give you some tips for this issue:
1. Try not to scan for many regions at once (which I guess you are doing) - each region sets up one filter, and after constant number of filters, Samsung will fail it's BLE scan.
2. I don't know if this bug was fixed on Samsung side, by try to update your software.
3. If everything fails, we have a special flag prepared to turn off Hardware Filtering - in your Android Manifest add: `<meta-data android:name="disable_hardware_filtering" android:value="true" />`
4. By the way here is a related issue: https://github.com/Estimote/Android-SDK/issues/153 

I hope you will handle this problem :)

**Closed** 2016-12-19 13:50 UTC
