### ISSUE TITLE
Android N Beacon Background Scanning Doze Mode

### ISSUE THREAD

**Issue by sbrkx** [Estimote/Android-SDK#161] opened 2016-08-04 16:39 UTC
When using the latest estimote SDK it appears to me that beacon scanning in background does not work even when the phone is being moved all  the time.
Do you have plans to restore background scanning in all doze steps?
My app does not use internet, I just need to safely rely on beacon detection in background even at high scanning intervals.

Thanks

**Comment by pawelDylag** [comment] 2016-08-08 08:34
Hello @sbrkx !

The problem with DOZE mode is that it heavily affects system timer invocations. Unfortunately this is the only way of scheduling available on Android - for easy background monitoring, which will last even if your app is killed, with the help of services. You need to have in mind, that the only possible time to do the scan in Doze is to use maintenance windows created by the system. We are really limited by those boundaries, and in result, bg monitoring is so unstable for now. 
We are working on optimising our SDK for every new Android release, and hopefully we will do some updates for new Doze changes :)

**Comment by sbrkx** [comment] 2016-08-08 09:05
Hi Pawel
thanks for your reply :)
We heavily rely on Estimote in our setup as we have around 400 beacons that we use in our venues which are used in that background scanning context.
So this would be a serious limitation but what you are saying is exactly what I'm experiencing now when I look at the debugger after putting the device into IDLE state. As soon as I put IDLE_MAINTENANCE the bluetooth scans continue, also I receive exit events that probably have been at the time the device was idle.
So as far as I understand the google docs when the device is MOVING (as a customer that has the phone in the pocket) doze should NOT affect the background capabilities. But while I had my own tests running I could not detect any BT scans in background even when moving the device around...

So did you experience the same thing when the device was in motion?

I'm currently testing with latest SDK, Android N latest preview on a Nexus 5X

**Comment by pawelDylag** [comment] 2016-08-08 09:44
According to Google's documentation, Doze should not affect BT while walking. By the way, check, if your phone is not using "batch scan". In such state, your BT scanner will sometimes return results really, really inexact.  Unfortunately, efforts for better battery saving in Android has reduced the overall responsiveness of BT stack. As far as I know, background scan is working pretty well on our version of N developer preview. Anyway, we will inspect this case and test Doze on various models.

**Comment by sbrkx** [comment] 2016-08-09 07:20
What do you mean with "batch scan"? I'm simply using estimote SDK according to the Docs. How can I check for that?

**Comment by pawelDylag** [comment] 2016-08-10 07:49
@sbrkx 
Batch scan is automatically being used by some devices that supports it. It is complicating our SDK work, because the system decides when to return bluetooth scan results - and we can not do anything about this. So that sometimes makes your results to be delayed or returned within inexact period. Thank you for reporting that - we will definitely push some more updates for Doze soon :)

**Comment by sbrkx** [comment] 2016-09-14 21:03
@pawelDylag 
I was pretty looking forward to the latest SDK update as it should fix the issues with background scanning in android doze. However, I still get the following messages by the system:
E/BtGatt.GattService: App 'xxx' is scanning too frequently

That's irritating because at the same time this:
W/EstimoteSDK: com.estimote.sdk.service.internal.bluetooth.NougatScanScheduler.modifyScanPeriodsForNougat:284 Scan period is too short for Android Nougat. Changed scan time to 6000 ms, and wait time to 1 ms. Nougat allows only max 5 possible scan start/stops per 30s.

appears in my logs.
The sad thing is also that when entering IDLE state in doze mode, scanning is still stopping completly. :(

**Comment by pawelDylag** [comment] 2016-09-15 12:31
Hello @sbrkx 

Sorry to hear that. We are working on improving this solution, but the problem is that we need to change major part of our architecture for that. Here are some tips:
1. While in Doze mode, all alarms are being triggered only on maintenance windows - we are strongly dependent on that alarm system, so our SDK can know when to trigger scanning (we are talking here about monitoring, because ranging is mainly for foreground scan, which doesn't occur while your phone is in Doze mode)
2. Every change of already running scan will trigger it's restart - so it happens every time you start/stop, add new listener for different packet or change scan periods. This time you need to check your code, if you are not shuffling with scan settings while scanning. 
3. I suggest you to setup your background scan (for monitoring) to `(scan=6000, wait=0)` or more. You will be still notified on enter/on exit while scanning.

We are currently developing more advanced support for N so stay tuned.

**Comment by amitsood** [comment] 2017-01-05 06:53
Hello, Any update on this. I too see errors saying "E/BtGatt.GattService: App 'xxx' is scanning too frequently".

**Comment by pawelDylag** [comment] 2017-04-19 14:56
Hello @amitsood @sbrkx 

We introduced some further improvements for Nougat devices. Please checkout the version `1.0.2` :)
You may also want to play with new method in our `BeaconManager` class - read more about it in our Javadocs :)

```Java
 /**
   * Since Nougat, every application is allowed to start/stop BLE scan a maximum of 5 times per 30s.
   * Tweaking this delay prevents many scan start/stop events, which resulted in "App XXX is scanning too frequently" logs.
   * All start/stop requests are buffered and the most recent is executed after the delay time.
   * Here is a little example to visualise you the problem:
   *
   * -----
   * 12:10:10 - User navigates to list of nearby devices -> Start monitoring
   * 12:10:11 - User clicks on selected beacon from the list -> Stop monitoring, start ranging
   * 12:10:12 - "Oops! Wrong beacon, I need to choose another one!" and he clicks 'back' button -> Stop ranging, start monitoring
   * 12:10:13 - Correct beacon is selected -> Stop monitoring, start ranging.
   * -----
   *
   * Result: 4 scan starts in about 3 seconds. The next scan cycle will be blocked for 30s due to Android 7.0 restrictions.
   * You can tweak this delay to avoid such situations.
   *
   * Pros: SDK will be more resilient to user interactions resulting in many start/stop requests.
   * Cons: The scan results will be delivered with a slight delay shortly after start.
   *
   * @param delayMillis delay in milliseconds. Must be greater or equal to zero. The default delay value is set to 1.5s (1500millis).
   */
beaconManager.setScanRequestDelay(delayMillis);
```

I must admit that those changes are not an ultimate solution, but the overall performance should be much better :)

**Comment by pawelDylag** [comment] 2017-05-02 12:55
Closing due to low activity. If anything changes, please reopen this issue.

**Closed by pawelDylag** 2017-05-02 12:55 UTC
Labels: bug
