### ISSUE TITLE
Huawei ALE-L21 - Scanning doesn't restart, after disabling and enabling bluetooth 

### ISSUE THREAD

**Issue by gbtt** [Estimote/Android-SDK#142] opened 2016-02-09 08:02 UTC
Hi, I have the following problem when turning bluetooth off and then on:

Device: Huawei P8 Lite, also known as Huawei ALE-L21
Estimote SDK: 0.9.7
Android: 5.0.1

How to reproduce it:
- Open my app with bluetooth enabled (everything is ok: I see beacons on logcat)
- Turn off bluetooth
- Turn on bluetooth. I get this error:

```
02-09 08:37:34.079 24621-24764/it.myexample.app I/EstimoteSDK: com.estimote.sdk.service.BeaconService$4$2.run:-1 Bluetooth is ON: resuming scanning
02-09 08:37:34.099 24621-24764/it.myexample.app E/BluetoothLeScanner: application registeration exception
                                                                        android.os.DeadObjectException
                                                                            at android.os.BinderProxy.transactNative(Native Method)
                                                                            at android.os.BinderProxy.transact(Binder.java:496)
                                                                            at android.bluetooth.IBluetoothGatt$Stub$Proxy.registerClient(IBluetoothGatt.java:851)
                                                                            at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.startRegisteration(BluetoothLeScanner.java:239)
                                                                            at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:132)
                                                                            at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:101)
                                                                            at com.estimote.sdk.service.internal.LollipopBluetoothAdapter.start(Unknown Source)
                                                                            at com.estimote.sdk.service.internal.CycleBluetoothScanner.start(Unknown Source)
                                                                            at com.estimote.sdk.service.BeaconService.startScanning(Unknown Source)
                                                                            at com.estimote.sdk.service.BeaconService.access$2000(Unknown Source)
                                                                            at com.estimote.sdk.service.BeaconService$4$2.run(Unknown Source)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
02-09 08:37:34.099 24621-24621/it.myexample.app E/EstimoteSDK: com.estimote.sdk.service.internal.LollipopBluetoothAdapter$1.onScanFailed:-1 Unable to start BLE scanning. Error code 3
02-09 08:37:34.109 24621-24621/it.myexample.app D/BluetoothLeScanner: could not find callback wrapper
02-09 08:37:34.109 24621-24621/it.myexample.app E/EstimoteSDK: com.estimote.sdk.service.internal.LollipopBluetoothAdapter$1.onScanFailed:-1 Unable to start BLE scanning. Error code 2
```
I don't get this problem on Samsung S4 and Nexus 5.

Thanks

**Comment by Poberro** [comment] 2016-03-12 21:01
Our investigation showed that Huawei ALE-L21 crashes if there are too many beacons around (even it's system Bluetooth device scanner in settings menu is crashing). If there are only few of them it works properly. BTW. Similar errors was plaguing first Androids with BLE. 
Error above is caused by Bluetooth service crashing and this must be fixed by device manufacturer.  SDK 0.10.0 should not crash when this error happens and it will report unstable Bluetooth behavior via additional error BeaconService.ERROR_BLUETOOTH_SCANNER_UNSTABLE returned by ErrorListener.

**Closed by Poberro** 2016-03-12 21:01 UTC
